### ISSUE TITLE
Block-scoped declarations 

### ISSUE THREAD

**Issue by shuvayan** [RasaHQ/rasa-nlu-trainer#20]
Hello,
While running the rasa_nlu_trainer I get an error at line 56 of server.js file as below:

`rasa-nlu-trainer
/usr/local/lib/node_modules/rasa-nlu-trainer/server.js:56
      let json
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
`
Please let me know how to fix this??
I have tried adding "use strict"; below let json as given in some forums but it does not work.

**Comment by azazdeaz** [comment]
Hello, you should update your nodejs version. Which version are you using?
