### ISSUE TITLE
UI failed to start

### ISSUE THREAD

**Issue by NagarajGond** [RasaHQ/rasa-nlu-trainer#22]
This is  issue can be solved if we use "use strict".

/usr/local/lib/node_modules/rasa-nlu-trainer/server.js:56
      let json
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

**Comment by amn41** [comment]
I think you have to update your node version

**Comment by NagarajGond** [comment]
Thank you,, I was using old node.
